[pytest]
markers =
    url: Verify GUVI URL
    title: Verify webpage title
    loginbutton: Verify login button
    signup: Verify sign-up button
    signupnavigation: Verify sign-up page navigation
    performlogin: Verify login with valid credentials
    invalidcredentials: Verify login with invalid credentials
    menu: Verify menu items
    dobby: Verify Dobby assistant
    logout: Verify logout functionality