[pytest]

markers =
    login: Tests related to login functionality
    invalid:Tests with invalid credentials
    logout: Tests related to logout functionality
    carticon:Tests cart icon visibility
    productselection:Tests related to random product selection
    cart: Tests related to cart functionality
    cart_details: Tests related to cart product details
    checkout: Tests related to checkout functionality
    sorting: Tests related to product sorting
    reset: Tests related to Reset App State

addopts = -v

testpaths = step_defs

python_files = test_*.py

bdd_features_base_dir = features