[pytest]

pythonpath= .

markers =
    login: Validating login using various credentials
    validurl: Verifying the OrangeHRM URL is accessible
    loginfields: Validating the presence of login fields
    menu: Verifying main menu items after login
    newuser: Creating a new user and validating login
    userlist: Validating the newly created user in admin user list
    forgotpassword: Verifying forgot password functionality
    myinfo: Validating menu items under My Info
    leave: Assigning leave and verifying assignment
    claimrequest: Initiating and verifying a claim request

addopts = -v